### PR TITLE
Make scripts into extensions

### PR DESCRIPTION
**Pull request by dpvc**
This pull request turns the scripts like `Semantic-MathML.js` into actual extensions, so that they can be loaded by MathJax using its synchronization process for extensions.  This should resolve the remaining timing issue from #58, without requiring any chances to SRE.  The `Semantic-MathML` extension now forces the loading of SRE, and the `Semantic-Collapse` forces loading of `Semantic-MathML` (so that users don't have to know the internal dependancies).  I've also added a custom path (`[RespEq]`) so that the extensions can be loaded via `[RespEq]/Semantic-Math`, and so on.  Similarly, I added `[SRE]` for where the SRE is loaded by `Semantic-MathML`.  If it is not specified by the page, then the current progressiveaccess.com address is used, but this allows it to be loaded locally or from the third-party repository if we want.

I've also reorganized the structure of the Semantic-Lab directory to separate out the extensions from the examples from the labs themselves, and renamed the labs to make their names less redundant.  I fixed up the `*-linebreak` labs to work with the current versions of the extensions (though I'm not sure why they seem to be deleted and re-added below, as I renamed them just like I did the others). 

The functionality of the `Semantic-Action-*` scripts have previously been moved to the SRE, so I've removed those files.

Let me know if you have any problems with the new organization.  Otherwise, I'll merge the changes in a day or two.

### CODE REVIEW

**Comment by zorkow** [comment]
There is now a problem with the walker demo that it does not switch of collapse.

**Comment by dpvc** [comment]
OK, give it a try now.  It should be disabled now.

**Comment by zorkow** [comment]
LGTM.

**Comment by zorkow** [comment]
I hit the wrong button!

**Pull request merged**
