### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by zorkow**
Fixes the default value for test equations.

### CODE REVIEW

**Comment by pkra** [comment]
LGTM.

**Comment by dpvc** [comment]
This change is not correct.  The Current value was set earlier in [line 192](https://github.com/mathjax/MathJax-RespEq/blob/6f1ddd73a265f7f04b6c03370ca3fbe9fb742a2d/Semantics-Lab/Semantic-Lab.js#L192), to the value that was passed to it from the URL options (the last saved value).  Setting it to 0 will override that.

Can you say what problem you are trying to solve?  Some browsers do their own form input caching, and it may be that that is causing some issues.  The correct solution may be to set the value of the input field explicitly to the `lab.Current` value, not set `lab.Current` to 0.

@pkra, you were a bit quick off the draw to merge this.  Did you test it out to see if it worked as expected?  I didn't have a chance to look through the code to see what the changes were, even.

**Comment by zorkow** [comment]
It gave me a NaN as value return value for this.Current.
Even the initial value of Lab.Current was NaN.

Volker

**Comment by dpvc** [comment]
What does the URL look like?

**Comment by dpvc** [comment]
Perhaps changing line 192 to be

      Lab.example.value = defaults[1]; Lab.Current = parseInt(defaults[1]) || 0;

would do the trick.

**Comment by zorkow** [comment]
Right, I can now see the assignment (that statement is double parked ;-)

Still parseInt("") is NaN.

Maybe change line 172 to
  var defaults = [null,0,

**Comment by dpvc** [comment]
Sure, that works, too.

**Pull request merged**
