### PR TITLE
add build tools

### PR DESCRIPTION
**Pull request by pkra**
See also #95

### CODE REVIEW

**Comment by pkra** [comment]
FYI, I've pushed a copy of the dist to https://beta.mathjax.org/mathjax/contrib/a11y and switched http://codepen.io/pkra/pen/yOWrWQ to that.

**Comment by dpvc** [comment]
These don't seem to be the latest versions (they don't have the last two commit that I did last week -- looks like you didn't pull the latest version before making your new branch).  If you add those commits, you will be able to simplify the code pen to only create the path for Contrib, and then load `[Contrib]/a11y/Accessibility-Extension.js` and drop the `RespEq` references entirely.

**Comment by pkra** [comment]
> These don't seem to be the latest versions 

Thanks, I'll update them.

Is the PR ok though?

**Comment by pkra** [comment]
> Thanks, I'll update them.

Update beta.mathjax.org and the codepen example. Looking good.

**Pull request merged**
