### PR TITLE
Adds MML classes in SVG configuration.

### PR DESCRIPTION
**Pull request by zorkow**
Addresses issue #32.

### CODE REVIEW

**Comment by pkra** [comment]
LGTM.

**Comment by dpvc** [comment]
I was going to say that an alternative to this would be to have the collapsing code (which inserts the mactions) mark the mactions with its own class name, so that (a) you don't need to turn on MML classes (so that the SVG is reduced in complexity and size), and (b) you can looks for the same class name in all the output modes, since it will be kept the same for them all.

**Comment by pkra** [comment]
@dpvc happy to revert and follow your suggestion.

**Comment by zorkow** [comment]
I understand the reasoning. However, the additional structure makes it easier for the walker. In general for SVG accessibility more structure is better than less. 
What is the additional complexity? Is it a constant factor?

**Comment by dpvc** [comment]
OK, sounds good.  Leave it as is.

**Comment by dpvc** [comment]
> What is the additional complexity? Is it a constant factor?

Sorry forgot to answer this.  No, I don't think it is constant, but haven't tried to measure it exactly.  It consists of removing nested groups that are not necessary. so an mrow consisting of an mn, an mo, and an mn with `addMMLclasses` set to `true` would normally have a `g` element for each of the MathML elements, but without `addMMLclasses`, only the outer `g` for the `mrow` would be retained, and it would contain three path elements (assuming one character for each of the token elements).  If that `g` were a child of some other `<g>` higher up in the MathML structure, it could also be removed.

**Pull request merged**
