### PR TITLE
Refactor aria region

### PR DESCRIPTION
**Pull request by zorkow**
Refactors ARIA region and adds an initial announcement about navigatable Maths expressions.

### CODE REVIEW

**Comment by zorkow** [comment]
I've tested it with ChromeVox, Jaws and NVDA (Win 7), Chrome, IE, Firefox. Results similar to matrix. ChromeVox has the occassional D I V problem.

**Comment by pkra** [comment]
https://github.com/mathjax/MathJax-RespEq/wiki/Support-Matrix-a11y-tool#pull-54 

Only issue is the regression in WindowEyes with Chrome.

I think we should go with this; the improvements far outweigh this regression.

**Comment by pkra** [comment]
Thanks. WinXP, Earcon over http in Chrome is fixed now.

**Comment by zorkow** [comment]
So that's ready to merge then.

**Pull request merged**
